apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jkzp8vehy-go 
  janus-idp.io/tekton: jkzp8vehy-go
  backstage.io/kubernetes-id: jkzp8vehy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jkzp8vehy-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  